const SUPABASE_URL = 'https://vxnlycbuacrielnhjqqi.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_rwF9RZvjKHXtB1fjCTkzfw_x8xrwKQH';
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const state = {
  user:null, profile:null, dashboard:{}, categories:[], threads:[], posts:[], soundCards:[], users:[], reports:[], events:[], notifications:[], uploads:[], blocks:[], settings:{}, activePanel:'dashboard', edit:null
};
const $ = id => document.getElementById(id);
const qsa = sel => [...document.querySelectorAll(sel)];
const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const fmt = v => v ? new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)) : '—';
const roleOrder = ['owner','admin','moderator','trusted_user','user','muted','banned'];
const permissionKeys = ['can_view_admin','can_moderate_content','can_edit_posts','can_delete_posts','can_lock_threads','can_manage_reports','can_ban_users','can_suspend_users','can_manage_roles','can_manage_categories','can_manage_settings','can_manage_html_blocks','can_manage_antispam','can_manage_uploads','can_manage_integrations','can_view_audit_logs'];
const panelCopy = {
  dashboard:['Dashboard','Stato forum, rischi recenti, azioni staff e metriche principali.'],
  moderation:['Moderazione contenuti','Modifica, nascondi, ripristina, chiudi, approva e respingi contenuti.'],
  reports:['Segnalazioni','Gestisci segnalazioni aperte e chiudi casi moderati.'],
  users:['Utenti & ruoli','Ruoli, gruppi, ban, mute, trusted user e profili artista.'],
  permissions:['Permessi','Matrice granulare dei poteri per ruolo.'],
  categories:['Categorie','Crea, modifica, ordina ed elimina categorie.'],
  security:['Sicurezza','Limiti operativi, policy accesso, log retention e host consentiti.'],
  antispam:['Anti-spam','Parole vietate, domini vietati, cooldown e soglie automatiche.'],
  uploads:['Upload controllati','MIME whitelist, dimensione massima, bucket e file tracciati.'],
  notifications:['Notifiche','Avvisi interni per utenti, staff e sicurezza.'],
  integrations:['Integrazioni esterne','Webhook, email admin e whitelist embed.'],
  blocks:['Editor HTML/CSS','Blocchi frontend salvati nel database.'],
  rules:['Regole sito','Regolamento pubblico e criteri di moderazione.'],
  audit:['Audit log','Cronologia completa delle azioni privilegiate.']
};

function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3200)}
function isStaff(){return ['owner','admin','moderator'].includes(state.profile?.role)}
function isAdmin(){return ['owner','admin'].includes(state.profile?.role)}
async function token(){const {data}=await db.auth.getSession();return data.session?.access_token || ''}
async function forumApi(action,payload={}){const t=await token(); if(!t) throw new Error('AUTH_REQUIRED'); const res=await fetch(`${SUPABASE_URL}/functions/v1/forum-api`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`,'apikey':SUPABASE_ANON_KEY},body:JSON.stringify({action,payload})}); const json=await res.json().catch(()=>({})); if(!res.ok || json.error) throw new Error(json.error || 'EDGE_FUNCTION_ERROR'); return json.data;}
async function adminAction(op,payload={}){return forumApi('admin-action',{op,...payload})}
async function loadSession(){const {data}=await db.auth.getSession();state.user=data.session?.user||null;if(!state.user){state.profile=null;return}const {data:profile}=await db.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=profile||null}
function renderAuth(){const badge=$('userBadge'); if(!state.user){badge.textContent='Ospite';$('loginBtn').classList.remove('hidden');$('logoutBtn').classList.add('hidden');$('authGate').classList.remove('hidden');return} badge.textContent=`${state.profile?.display_name||state.user.email} · ${state.profile?.role||'user'}`;$('loginBtn').classList.add('hidden');$('logoutBtn').classList.remove('hidden');$('authGate').classList.toggle('hidden',isStaff());}
async function bootstrap(){bindEvents();applySavedTheme();await loadSession();renderAuth();if(isStaff()) await refreshAll();}
function bindEvents(){
  $('themeBtn').onclick=toggleTheme;$('loginBtn').onclick=()=>$('authDialog').showModal();$('gateLoginBtn').onclick=()=>$('authDialog').showModal();$('closeAuthBtn').onclick=()=>$('authDialog').close();$('cancelAuthBtn').onclick=()=>$('authDialog').close();$('doLoginBtn').onclick=login;$('logoutBtn').onclick=logout;$('gateRefreshBtn').onclick=async()=>{await loadSession();renderAuth();if(isStaff())refreshAll()};$('refreshBtn').onclick=refreshAll;$('openForumBtn').onclick=()=>location.href='forum.html';
  qsa('.admin-side-nav button').forEach(btn=>btn.onclick=()=>setPanel(btn.dataset.panel));
  ['contentReloadBtn','reportsReloadBtn','auditReloadBtn'].forEach(id=>$(id).onclick=renderCurrentLists);
  ['contentSearch','contentStatus','contentCategory','contentType','reportStatus','userSearch','userRoleFilter','auditSearch','auditAction'].forEach(id=>$(id)?.addEventListener('input',renderCurrentLists));
  $('recalcGroupsBtn').onclick=async()=>{await adminAction('recalculate-groups');toast('Gruppi ricalcolati.');await refreshAll()};
  $('savePermissionsBtn').onclick=savePermissions;$('categoryForm').onsubmit=saveCategory;$('catResetBtn').onclick=resetCategoryForm;$('securityForm').onsubmit=e=>saveSettingForm(e,'security');$('antispamForm').onsubmit=e=>saveSettingForm(e,'antispam');$('uploadForm').onsubmit=e=>saveSettingForm(e,'uploads');$('integrationsForm').onsubmit=e=>saveSettingForm(e,'integrations');$('rulesForm').onsubmit=e=>saveRules(e);$('notificationForm').onsubmit=sendNotification;$('blockForm').onsubmit=saveBlock;$('blockTemplateBtn').onclick=insertBlockTemplate;$('blockPreviewBtn').onclick=previewBlock;
  $('closeEditBtn').onclick=()=>$('editDialog').close();$('cancelEditBtn').onclick=()=>$('editDialog').close();$('editForm').onsubmit=submitEdit;
}
function applySavedTheme(){document.body.dataset.theme=localStorage.getItem('incForumTheme')||'dark'}
function toggleTheme(){const next=document.body.dataset.theme==='light'?'dark':'light';document.body.dataset.theme=next;localStorage.setItem('incForumTheme',next)}
async function login(){try{const {error}=await db.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});if(error)throw error;$('authDialog').close();await loadSession();renderAuth();if(isStaff())await refreshAll();else toast('Profilo non autorizzato al pannello admin.')}catch(e){$('authMessage').textContent=e.message}}
async function logout(){await db.auth.signOut();state.user=null;state.profile=null;renderAuth();}
function setPanel(name){state.activePanel=name;qsa('.admin-side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));qsa('.admin-panel').forEach(p=>p.classList.remove('active'));$(`panel${name[0].toUpperCase()+name.slice(1)}`)?.classList.add('active');$('panelTitle').textContent=panelCopy[name]?.[0]||name;$('panelSubtitle').textContent=panelCopy[name]?.[1]||'';renderCurrentLists();}
async function refreshAll(){if(!isStaff())return;try{const data=await forumApi('get-admin-dashboard-complete').catch(()=>forumApi('get-admin-dashboard'));state.dashboard=data||{};state.users=data.users||[];state.events=data.events||[];state.reports=data.reports||[];state.threads=data.threads||[];state.posts=data.posts||[];state.soundCards=data.sound_cards||[];state.notifications=data.notifications||[];state.uploads=data.uploads||[];state.blocks=data.admin_blocks||[];state.settings=data.settings||{};await loadPublicFallbacks();renderAll();toast('Dati aggiornati.')}catch(e){toast(e.message)}}
async function loadPublicFallbacks(){const [{data:cats},{data:threads},{data:posts},{data:sound},{data:blocks},{data:settings}]=await Promise.all([db.from('category_overview').select('*').order('sort_order'),db.from('thread_overview').select('*').order('last_activity_at',{ascending:false}).limit(500),db.from('post_overview').select('*').order('created_at',{ascending:false}).limit(500),db.from('sound_cards').select('*').order('created_at',{ascending:false}).limit(500),db.from('admin_blocks').select('*').order('sort_order'),db.from('site_settings').select('*')]);state.categories=cats||state.categories||[];if(!state.threads.length)state.threads=threads||[];if(!state.posts.length)state.posts=posts||[];if(!state.soundCards.length)state.soundCards=sound||[];if(!state.blocks.length)state.blocks=blocks||[];(settings||[]).forEach(s=>state.settings[s.key]=s.value)}
function renderAll(){renderDashboard();renderCategoryOptions();renderModeration();renderReports();renderUsers();renderPermissions();renderCategories();renderSettings();renderNotifications();renderBlocks();renderAudit();}
function renderCurrentLists(){renderDashboard();renderModeration();renderReports();renderUsers();renderAudit();}
function renderDashboard(){const stats=state.dashboard.stats||{};$('mUsers').textContent=stats.users_count??state.users.length??'—';$('mThreads').textContent=stats.threads_count??state.threads.filter(x=>!x.is_deleted).length;$('mPosts').textContent=stats.posts_count??state.posts.filter(x=>!x.is_deleted).length;$('mReports').textContent=state.reports.filter(r=>r.status==='open').length;$('mPending').textContent=[...state.threads,...state.posts].filter(x=>x.moderation_status==='pending').length;$('mUploads').textContent=state.uploads.length||'0';$('dashEvents').innerHTML=state.events.slice(0,8).map(eventRow).join('')||emptyRow('Nessun log.');$('dashRisks').innerHTML=[...state.reports.filter(r=>r.status==='open').slice(0,5).map(reportRow),...state.events.filter(e=>/spam|ban|security|error|forbidden/i.test(e.action||'')).slice(0,5).map(eventRow)].join('')||emptyRow('Nessun rischio aperto.');}
function renderCategoryOptions(){const opts='<option value="all">Tutte le categorie</option>'+state.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.icon||'◆')} ${esc(c.name)}</option>`).join('');$('contentCategory').innerHTML=opts;}
function renderModeration(){let list=[];const type=$('contentType').value;if(type==='threads')list=state.threads.map(x=>({...x,_type:'thread'}));if(type==='posts')list=state.posts.map(x=>({...x,_type:'post',title:`Risposta a ${x.thread_id}`}));if(type==='sound_cards')list=state.soundCards.map(x=>({...x,_type:'sound_card',title:x.title,body:x.description,author_name:x.artist,is_deleted:x.is_hidden,moderation_status:x.is_hidden?'deleted':'approved'}));const q=$('contentSearch').value.toLowerCase().trim(), st=$('contentStatus').value, cat=$('contentCategory').value;list=list.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(st==='all'||(st==='deleted'?x.is_deleted:x.moderation_status===st))&&(cat==='all'||x.category_id===cat));$('moderationList').innerHTML=list.slice(0,250).map(contentRow).join('')||emptyRow('Nessun contenuto trovato.');}
function contentRow(x){const hidden=x.is_deleted||x.is_hidden;const status=hidden?'deleted':(x.moderation_status||'approved');const meta=[x._type,x.category_name,x.author_name||x.author_id,fmt(x.created_at),`spam ${x.spam_score||0}`].filter(Boolean).join(' · ');return `<article class="admin-row"><div><h4>${statusChip(status)} ${esc(x.title||x.body?.slice(0,80)||'Senza titolo')}</h4><p>${esc((x.body||x.description||'').slice(0,260))}</p><small>${esc(meta)}</small></div><div class="admin-row-actions">${x._type==='thread'?threadActions(x):x._type==='post'?postActions(x):soundActions(x)}</div></article>`}
function threadActions(t){return `<button onclick="editThread('${t.id}')">Modifica</button><button onclick="lockThread('${t.id}',${!t.is_locked})">${t.is_locked?'Riapri':'Chiudi'}</button><button class="admin-ok" onclick="setThreadStatus('${t.id}','approved')">Approva</button><button class="admin-warn" onclick="setThreadStatus('${t.id}','pending')">Revisione</button><button class="admin-danger" onclick="hideThread('${t.id}',${!t.is_deleted})">${t.is_deleted?'Ripristina':'Nascondi'}</button>`}
function postActions(p){return `<button onclick="editPost('${p.id}')">Modifica</button><button class="admin-ok" onclick="setPostStatus('${p.id}','approved')">Approva</button><button class="admin-warn" onclick="setPostStatus('${p.id}','pending')">Revisione</button><button class="admin-danger" onclick="hidePost('${p.id}',${!p.is_deleted})">${p.is_deleted?'Ripristina':'Nascondi'}</button>`}
function soundActions(s){return `<button onclick="editSound('${s.id}')">Modifica</button><button class="admin-danger" onclick="hideSound('${s.id}',${!s.is_hidden})">${s.is_hidden?'Ripristina':'Nascondi'}</button>`}
function renderReports(){let list=state.reports;const st=$('reportStatus').value;if(st!=='all')list=list.filter(r=>r.status===st);$('reportsList').innerHTML=list.map(reportRowFull).join('')||emptyRow('Nessuna segnalazione.');}
function renderUsers(){let list=state.users;const q=$('userSearch').value.toLowerCase().trim(), role=$('userRoleFilter').value;list=list.filter(u=>(!q||JSON.stringify(u).toLowerCase().includes(q))&&(role==='all'||u.role===role));$('usersList').innerHTML=list.map(userRow).join('')||emptyRow('Nessun utente.');}
function renderPermissions(){const current=state.settings.role_permissions||defaultPermissions();let html='<table><thead><tr><th>Permesso</th>'+roleOrder.map(r=>`<th>${esc(r)}</th>`).join('')+'</tr></thead><tbody>';for(const key of permissionKeys){html+=`<tr><td><strong>${esc(key)}</strong></td>`+roleOrder.map(role=>`<td><input type="checkbox" data-perm="${key}" data-role="${role}" ${current[role]?.includes(key)?'checked':''}></td>`).join('')+'</tr>'}html+='</tbody></table>';$('permissionsMatrix').innerHTML=html;}
function renderCategories(){$('categoriesList').innerHTML=state.categories.map(c=>`<article class="admin-row"><div><h4>${esc(c.icon||'◆')} ${esc(c.name)}</h4><p>${esc(c.description||'')}</p><small>${esc(c.slug)} · ordine ${c.sort_order??50} · ${c.thread_count??0} discussioni</small></div><div class="admin-row-actions"><button onclick="fillCategory('${c.id}')">Modifica</button><button class="admin-danger" onclick="deleteCategory('${c.id}')">Elimina</button></div></article>`).join('')||emptyRow('Nessuna categoria.');}
function renderSettings(){const s=state.settings;$('secRequireEmail').value=String(s.security?.require_email_verified??true);$('secMinAgeLinks').value=s.security?.min_account_age_to_post_links_hours??24;$('secMaxPostsHour').value=s.security?.max_posts_per_hour??3;$('secMaxCommentsHour').value=s.security?.max_comments_per_hour??8;$('secAutoHideReports').value=s.security?.auto_hide_reports_threshold??3;$('secLogRetention').value=s.security?.log_retention_days??180;$('secAllowedHosts').value=(s.security?.allowed_hosts||[]).join(', ');$('spamHoldScore').value=s.antispam?.hold_score??8;$('spamMaxLinks').value=s.antispam?.max_links_per_post??3;$('spamPostCooldown').value=s.antispam?.post_cooldown_seconds??600;$('spamCommentCooldown').value=s.antispam?.comment_cooldown_seconds??120;$('blockedWords').value=(s.antispam?.blocked_words||[]).join('\n');$('blockedDomains').value=(s.antispam?.blocked_domains||[]).join('\n');$('upEnabled').value=String(s.uploads?.enabled??true);$('upMaxMb').value=s.uploads?.max_mb??6;$('upMimeTypes').value=(s.uploads?.mime_types||['image/jpeg','image/png','image/webp','image/gif']).join(', ');$('upBucket').value=s.uploads?.bucket||'forum-media';$('upOrphanDays').value=s.uploads?.orphan_delete_days??30;$('intDiscordEnabled').value=String(s.integrations?.discord_enabled??false);$('intTelegramEnabled').value=String(s.integrations?.telegram_enabled??false);$('intDiscordUrl').value=s.integrations?.discord_webhook_url||'';$('intAdminEmail').value=s.integrations?.admin_email||'';$('intEmbedHosts').value=(s.integrations?.embed_hosts||[]).join(', ');$('rulesTitle').value=s.rules?.title||'Regolamento INC. Forum';$('rulesBody').value=s.rules?.body||'';$('uploadsList').innerHTML=state.uploads.map(uploadRow).join('')||emptyRow('Nessun upload tracciato.');$('securityEvents').innerHTML=state.events.filter(e=>/security|forbidden|spam|upload|auth/i.test(e.action||'')).slice(0,60).map(eventRow).join('')||emptyRow('Nessun evento sicurezza.');}
function renderNotifications(){$('notificationsList').innerHTML=state.notifications.map(n=>`<article class="admin-row"><div><h4>${esc(n.type)} · ${fmt(n.created_at)}</h4><p>${esc(JSON.stringify(n.payload||{}))}</p><small>${n.is_read?'letta':'non letta'} · ${esc(n.user_id||'')}</small></div></article>`).join('')||emptyRow('Nessuna notifica.');}
function renderBlocks(){$('blocksList').innerHTML=state.blocks.map(b=>`<article class="admin-row"><div><h4>${statusChip(b.is_active?'approved':'deleted')} ${esc(b.title)}</h4><p>${esc(b.location)} · ordine ${b.sort_order??100}</p><small>${fmt(b.updated_at)}</small></div><div class="admin-row-actions"><button onclick="fillBlock('${b.id}')">Modifica</button><button onclick="toggleBlock('${b.id}')">${b.is_active?'Disattiva':'Attiva'}</button><button class="admin-danger" onclick="deleteBlock('${b.id}')">Elimina</button></div></article>`).join('')||emptyRow('Nessun blocco.');}
function renderAudit(){let list=state.events;const q=$('auditSearch').value.toLowerCase().trim();if(q)list=list.filter(e=>JSON.stringify(e).toLowerCase().includes(q));const actions=[...new Set(state.events.map(e=>e.action).filter(Boolean))];$('auditAction').innerHTML='<option value="all">Tutte le azioni</option>'+actions.map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join('');const a=$('auditAction').value;if(a!=='all')list=list.filter(e=>e.action===a);$('auditList').innerHTML=list.map(eventRow).join('')||emptyRow('Nessun evento.');}
function userRow(u){const r=u.role||'user';return `<article class="admin-row"><div><h4>${esc(u.display_name||u.username||u.id)} ${statusChip(r)}</h4><p>${esc(u.bio||'')}</p><small>${esc(u.email||'')} ${esc(u.username||'')} · gruppo ${esc(u.user_group||'visitatore')} · ultimo accesso ${fmt(u.last_seen_at)}</small></div><div class="admin-row-actions"><select onchange="setUserRole('${u.id}',this.value)">${roleOrder.map(x=>`<option value="${x}" ${x===r?'selected':''}>${x}</option>`).join('')}</select><button onclick="toggleArtist('${u.id}',${!u.is_artist})">${u.is_artist?'Togli artista':'Artista'}</button><button onclick="setUserRole('${u.id}','muted')">Mute</button><button class="admin-danger" onclick="setUserRole('${u.id}','banned')">Ban</button></div></article>`}
function reportRow(r){return `<article class="admin-row"><div><h4>🚩 ${esc(r.target_type)} · ${esc(r.reason)}</h4><p>${fmt(r.created_at)} · ${esc(r.target_id)}</p></div></article>`}
function reportRowFull(r){return `<article class="admin-row"><div><h4>${statusChip(r.status)} ${esc(r.target_type)} · ${esc(r.reason)}</h4><p>Target: ${esc(r.target_id)} · Reporter: ${esc(r.reporter_id||'anon')}</p><small>${fmt(r.created_at)}</small></div><div class="admin-row-actions"><button class="admin-ok" onclick="resolveReport('${r.id}','resolved')">Risolvi</button><button onclick="resolveReport('${r.id}','dismissed')">Archivia</button></div></article>`}
function eventRow(e){return `<article class="admin-row"><div><h4>${esc(e.action)}</h4><p>${esc(e.target_type||'')} ${esc(e.target_id||'')} · actor ${esc(e.actor_id||'')}</p><small>${fmt(e.created_at)}</small></div><pre class="json-dump">${esc(JSON.stringify(e.metadata||{},null,2).slice(0,500))}</pre></article>`}
function uploadRow(u){return `<article class="admin-row"><div><h4>${esc(u.filename||u.path||u.id)}</h4><p>${esc(u.mime_type||'')} · ${Number(u.size_bytes||0)/1024|0} KB</p><small>${fmt(u.created_at)} · ${esc(u.user_id||'')}</small></div><div class="admin-row-actions"><button class="admin-danger" onclick="deleteUpload('${u.id}')">Elimina record</button></div></article>`}
function statusChip(s){return `<span class="status-chip status-${esc(s)}">${esc(s)}</span>`}
function emptyRow(msg){return `<article class="admin-row"><div><h4>${esc(msg)}</h4><p>Prova ad aggiornare o cambia filtro.</p></div></article>`}
function csv(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function lines(v){return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean)}
function defaultPermissions(){return {owner:permissionKeys,admin:permissionKeys.filter(k=>k!=='can_manage_roles'),moderator:['can_view_admin','can_moderate_content','can_edit_posts','can_delete_posts','can_lock_threads','can_manage_reports','can_view_audit_logs'],trusted_user:[],user:[],muted:[],banned:[]}}
async function savePermissions(){const perms={};roleOrder.forEach(r=>perms[r]=[]);qsa('#permissionsMatrix input').forEach(i=>{if(i.checked)perms[i.dataset.role].push(i.dataset.perm)});await adminAction('save-setting',{key:'role_permissions',value:perms,target_type:'setting'});state.settings.role_permissions=perms;toast('Permessi salvati.');}
async function saveCategory(e){e.preventDefault();await adminAction('category-upsert',{id:$('catId').value||undefined,name:$('catName').value,slug:$('catSlug').value,icon:$('catIcon').value,sort_order:Number($('catSort').value||50),description:$('catDescription').value,target_type:'category'});resetCategoryForm();await refreshAll();}
function resetCategoryForm(){$('categoryForm').reset();$('catId').value='';$('catIcon').value='◆';$('catSort').value=50}
window.fillCategory=id=>{const c=state.categories.find(x=>x.id===id);if(!c)return;$('catId').value=c.id;$('catName').value=c.name||'';$('catSlug').value=c.slug||'';$('catIcon').value=c.icon||'◆';$('catSort').value=c.sort_order??50;$('catDescription').value=c.description||'';scrollTo({top:0,behavior:'smooth'})}
window.deleteCategory=async id=>{if(!confirm('Eliminare categoria? Fallirà se contiene discussioni.'))return;await adminAction('category-delete',{id,target_type:'category'});await refreshAll()}
async function saveSettingForm(e,key){e.preventDefault();let value={};if(key==='security')value={require_email_verified:$('secRequireEmail').value==='true',min_account_age_to_post_links_hours:+$('secMinAgeLinks').value,max_posts_per_hour:+$('secMaxPostsHour').value,max_comments_per_hour:+$('secMaxCommentsHour').value,auto_hide_reports_threshold:+$('secAutoHideReports').value,log_retention_days:+$('secLogRetention').value,allowed_hosts:csv($('secAllowedHosts').value)};if(key==='antispam')value={hold_score:+$('spamHoldScore').value,max_links_per_post:+$('spamMaxLinks').value,post_cooldown_seconds:+$('spamPostCooldown').value,comment_cooldown_seconds:+$('spamCommentCooldown').value,blocked_words:lines($('blockedWords').value),blocked_domains:lines($('blockedDomains').value)};if(key==='uploads')value={enabled:$('upEnabled').value==='true',max_mb:+$('upMaxMb').value,mime_types:csv($('upMimeTypes').value),bucket:$('upBucket').value,orphan_delete_days:+$('upOrphanDays').value};if(key==='integrations')value={discord_enabled:$('intDiscordEnabled').value==='true',telegram_enabled:$('intTelegramEnabled').value==='true',discord_webhook_url:$('intDiscordUrl').value,admin_email:$('intAdminEmail').value,embed_hosts:csv($('intEmbedHosts').value)};await adminAction('save-setting',{key,value,target_type:'setting'});state.settings[key]=value;toast(`${key} salvato.`)}
async function saveRules(e){e.preventDefault();const value={title:$('rulesTitle').value,body:$('rulesBody').value,updated_at:new Date().toISOString()};await adminAction('save-setting',{key:'rules',value,target_type:'setting'});state.settings.rules=value;toast('Regole salvate.')}
async function sendNotification(e){e.preventDefault();await adminAction('send-notification',{type:$('notifType').value,target:$('notifTarget').value,title:$('notifTitle').value,body:$('notifBody').value,target_type:'notification'});$('notificationForm').reset();await refreshAll()}
async function saveBlock(e){e.preventDefault();await adminAction('admin-block-upsert',{id:$('blockId').value||undefined,title:$('blockTitle').value,location:$('blockLocation').value,sort_order:+$('blockSort').value,is_active:$('blockActive').value==='true',html:$('blockHtml').value,css:$('blockCss').value,target_type:'admin_block'});$('blockForm').reset();$('blockId').value='';await refreshAll()}
function insertBlockTemplate(){$('blockHtml').value='<section class="admin-block"><h2>Titolo blocco</h2><p>Testo del blocco visibile nel forum.</p><a href="https://example.com">Link</a></section>';$('blockCss').value='.admin-block{border:1px solid rgba(139,44,255,.35);border-radius:20px;padding:18px;background:linear-gradient(135deg,rgba(139,44,255,.16),rgba(72,215,255,.08))}.admin-block h2{margin-top:0}';previewBlock()}
function previewBlock(){const root=$('blockPreview');root.innerHTML=`<style>${$('blockCss').value}</style>${$('blockHtml').value}`}
window.fillBlock=id=>{const b=state.blocks.find(x=>x.id===id);if(!b)return;$('blockId').value=b.id;$('blockTitle').value=b.title||'';$('blockLocation').value=b.location||'forum_top';$('blockSort').value=b.sort_order??100;$('blockActive').value=String(b.is_active);$('blockHtml').value=b.html||'';$('blockCss').value=b.css||'';previewBlock();}
window.toggleBlock=async id=>{const b=state.blocks.find(x=>x.id===id);await adminAction('admin-block-upsert',{id,title:b.title,location:b.location,sort_order:b.sort_order,is_active:!b.is_active,html:b.html,css:b.css,target_type:'admin_block'});await refreshAll()}
window.deleteBlock=async id=>{if(!confirm('Eliminare blocco?'))return;await adminAction('admin-block-delete',{id,target_type:'admin_block'});await refreshAll()}
window.setUserRole=async(id,role)=>{if(!confirm(`Impostare ruolo ${role}?`))return;await adminAction('update-user',{id,patch:{role},target_type:'user'});await refreshAll()}
window.toggleArtist=async(id,is_artist)=>{await adminAction('update-user',{id,patch:{is_artist},target_type:'user'});await refreshAll()}
window.resolveReport=async(id,status)=>{await adminAction('resolve-report',{id,status,target_type:'report'});await refreshAll()}
window.editThread=id=>openEdit('thread',state.threads.find(x=>x.id===id));window.editPost=id=>openEdit('post',state.posts.find(x=>x.id===id));window.editSound=id=>openEdit('sound_card',state.soundCards.find(x=>x.id===id));
window.lockThread=async(id,is_locked)=>{await adminAction('update-thread',{id,is_locked,target_type:'thread'});await refreshAll()};
window.hideThread=async(id,is_deleted)=>{await adminAction('update-thread',{id,is_deleted,target_type:'thread'});await refreshAll()};
window.setThreadStatus=async(id,moderation_status)=>{await adminAction('update-thread',{id,moderation_status,target_type:'thread'});await refreshAll()};
window.hidePost=async(id,is_deleted)=>{await adminAction('update-post',{id,is_deleted,target_type:'post'});await refreshAll()};
window.setPostStatus=async(id,moderation_status)=>{await adminAction('update-post',{id,moderation_status,target_type:'post'});await refreshAll()};
window.hideSound=async(id,is_hidden)=>{await adminAction('update-sound-card',{id,is_hidden,target_type:'sound_card'});await refreshAll()};
window.deleteUpload=async id=>{if(!confirm('Eliminare record upload?'))return;await adminAction('delete-upload',{id,target_type:'upload'});await refreshAll()};
function openEdit(type,row){if(!row)return;state.edit={type,row};$('editTitle').textContent=`Modifica ${type}`;let html='';if(type==='thread')html=`<label class="span-2">Titolo<input name="title" value="${esc(row.title)}"></label><label class="span-2">Testo<textarea name="body" rows="8">${esc(row.body)}</textarea></label><label>Categoria<select name="category_id">${state.categories.map(c=>`<option value="${c.id}" ${c.id===row.category_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Stato<select name="moderation_status"><option ${row.moderation_status==='approved'?'selected':''}>approved</option><option ${row.moderation_status==='pending'?'selected':''}>pending</option><option ${row.moderation_status==='rejected'?'selected':''}>rejected</option></select></label>`;if(type==='post')html=`<label class="span-2">Testo<textarea name="body" rows="8">${esc(row.body)}</textarea></label><label>Stato<select name="moderation_status"><option ${row.moderation_status==='approved'?'selected':''}>approved</option><option ${row.moderation_status==='pending'?'selected':''}>pending</option><option ${row.moderation_status==='rejected'?'selected':''}>rejected</option></select></label>`;if(type==='sound_card')html=`<label>Titolo<input name="title" value="${esc(row.title)}"></label><label>Artista<input name="artist" value="${esc(row.artist)}"></label><label>Genere<input name="main_genre" value="${esc(row.main_genre)}"></label><label>Cover URL<input name="cover_url" value="${esc(row.cover_url||'')}"></label><label class="span-2">Descrizione<textarea name="description" rows="7">${esc(row.description||'')}</textarea></label>`;$('editFields').innerHTML=html;$('editDialog').showModal()}
async function submitEdit(e){e.preventDefault();const fd=new FormData(e.target);const p=Object.fromEntries(fd.entries());const {type,row}=state.edit;if(type==='thread')await adminAction('update-thread',{id:row.id,...p,target_type:'thread'});if(type==='post')await adminAction('update-post',{id:row.id,...p,target_type:'post'});if(type==='sound_card')await adminAction('update-sound-card',{id:row.id,...p,target_type:'sound_card'});$('editDialog').close();await refreshAll()}
bootstrap();
