-- Supabase schema per feedback.html / ZEROUAN INC.
-- Esegui questo nello SQL Editor di Supabase se la tabella non esiste già.

create table if not exists public.feedback_comments (
  id bigint generated by default as identity primary key,
  name text not null,
  comment text not null,
  created_at timestamptz not null default now()
);

alter table public.feedback_comments enable row level security;

drop policy if exists "Public can read feedback comments" on public.feedback_comments;
create policy "Public can read feedback comments"
on public.feedback_comments
for select
to anon
using (true);

drop policy if exists "Public can insert feedback comments" on public.feedback_comments;
create policy "Public can insert feedback comments"
on public.feedback_comments
for insert
to anon
with check (
  length(trim(name)) between 1 and 40
  and length(trim(comment)) between 1 and 800
);

create index if not exists feedback_comments_created_at_idx
on public.feedback_comments (created_at desc);
